# Site settings
title: Climate Treaty Texts from Paris COP21
short_title: Climate Treaty Negotiations at Paris COP21
description: |
    Making the treaty texts of the international climate change conference easy to find, understand and use
baseurl: ""
url: "http://cop21.okfnlabs.org" # the base hostname & protocol for your site
github_username:  okfn
github_repo:  cop21
paypal: admin@okfn.org
contact: https://discuss.okfn.org/t/cop21-negotiating-texts-project/1647

gems:
  - jekyll-redirect-from

googleanalytics: UA-33874954-37

markdown: kramdown

permalink: pretty

defaults:
  -
    scope:
      path: ""
    values:
      layout: page
      section: texts


related_projects:
  -
      name: OpenGovernmentData.org
      link: http://opengovernmentdata.org/
  -
      name: The DataHub
      link: http://datahub.io/
  -
      name: DataCatalogs.org
      link: http://datacatalogs.org/
  -
      name: OpenSpending.org
      link: http://openspending.org/
  -
      name: SchoolOfData.org
      link: http://schoolofdata.org/
  -
      name: OpenDefinition.org
      link: http://opendefinition.org/
  -
      name: Introducing Open Data
      link: http://okfn.org/opendata/
